metadata:
  version: 0.0.0
  notes: Created from Cell Editor
robot:
  name: Yaskawa GP7
  source: library
  library_name: Yaskawa-GP7.robot
  pose:
    xyz_mm: [0.0, 0.0, 330.0]
    rpy_deg: [0.0, 0.0, 0.0]
  home_joints_deg: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
frames: []
objects: []
object_classes: [tray, bottle, cup, bolt]
robot_connection:
  enabled: false
  port: 80
  driver: Motoman
  max_speed_percent: 30.0
  acceleration_percent: 50.0
