#!/usr/bin/env python
"""
23_launch_retrain.py
────────────────────
Package a dataset version for the Linux GPU training machine + print the
exact ultralytics command (training is OFF-REPO by design, see README).

Builds a combined dataset.yaml where TRAINING mixes real + synthetic images
but VALIDATION stays REAL-ONLY (synthetic val would flatter mAP — reviewers
will look for this).

Usage:
    python scripts/23_launch_retrain.py --synth data/synth/anchored_k2/dataset \
        --real data/real_dataset --version 1 --epochs 100 --seed 0
    # add --zip to also produce data/packages/dsv1.zip for transfer
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.utils import setup_logging  # noqa: E402

CLASS_NAMES = ["carton", "plastic_box", "wood_box", "metal_box"]  # paper dataset (synthgen.yaml)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--synth", nargs="*", default=[],
                        help="Synthetic dataset dir(s) (from 20 --make-labels)")
    parser.add_argument("--real", default=None,
                        help="Real dataset dir (ultralytics layout) — supplies val")
    parser.add_argument("--version", type=int, required=True,
                        help="Dataset version k (loop iteration)")
    parser.add_argument("--out", default="data/packages")
    parser.add_argument("--model", default="yolov8s-seg.pt")
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--imgsz", type=int, default=1280)
    parser.add_argument("--seed", type=int, default=0,
                        help="Train seed — paper reports mean±std over 3 seeds")
    parser.add_argument("--zip", action="store_true",
                        help="Also zip the referenced dataset dirs for transfer")
    return parser.parse_args()


def _resolve(p: str) -> Path:
    path = Path(p)
    return path if path.is_absolute() else PROJECT_ROOT / p


def main() -> int:
    args = parse_args()
    log = setup_logging("retrain")

    out_dir = _resolve(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    train_dirs: list[Path] = []
    for s in args.synth:
        d = _resolve(s)
        if not (d / "images" / "train").exists():
            log.error("Not an ultralytics dataset (images/train missing): %s", d)
            return 1
        train_dirs.append(d / "images" / "train")

    val_dir: Path | None = None
    if args.real:
        real = _resolve(args.real)
        if not (real / "images").exists():
            log.error("Real dataset dir has no images/: %s", real)
            return 1
        train_dirs.append(real / "images" / "train")
        val_dir = real / "images" / "val"
    if not train_dirs:
        log.error("Nothing to train on — pass --synth and/or --real")
        return 1
    if val_dir is None:
        log.warning("No --real dataset → validating on the FIRST synth val split. "
                    "For the paper, validation must be on REAL images.")
        val_dir = train_dirs[0].parent / "val"

    yaml_path = out_dir / f"dsv{args.version}.yaml"
    lines = ["# Combined dataset — generated by 23_launch_retrain.py",
             "train:"]
    lines += [f"  - {d.resolve().as_posix()}" for d in train_dirs]
    lines += [f"val: {val_dir.resolve().as_posix()}", "names:"]
    lines += [f"  {i}: {n}" for i, n in enumerate(CLASS_NAMES)]
    yaml_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log.info("Dataset yaml (train=%d source(s), val=%s) → %s",
             len(train_dirs), val_dir, yaml_path)

    if args.zip:
        roots = {d.parent.parent for d in train_dirs} | {val_dir.parent.parent}
        for root in sorted(roots):
            archive = out_dir / f"dsv{args.version}_{root.name}"
            shutil.make_archive(str(archive), "zip", root)
            log.info("Packed %s → %s.zip", root, archive)

    log.info("On the GPU machine (repeat with seed 0/1/2 for the paper):")
    log.info("  yolo segment train data=%s model=%s epochs=%d imgsz=%d seed=%d "
             "project=runs name=dsv%d_s%d",
             yaml_path.name, args.model, args.epochs, args.imgsz, args.seed,
             args.version, args.seed)
    log.info("Deploy: copy best.pt back to models/ and rerun 03_run_experiment.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
